# Site settings
title: Jazmin Collins Personal Website
description: Jazmin Collins
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jazmin Collins
user_description: Information Science PhD candidate with 10+ years of participation in various technology programs, competitions, conferences, and challenges. Specialties in machine learning through Python and GCP, computer vision with TensorFlow models and Javascript, tactile user interfaces for the visually-impaired, and virtual reality with Unity and C#. Best progamming languages are Java, Python, and SQL, with basic experience in C# and HTML/CSS.
user_title: #Learner of HCI and Accessibility
email: collinsjazmin.21@gmail.com
#twitter_username: lorem_ipsum
github_username:  https://github.com/jcollins-01
google_scholar: https://scholar.google.com/citations?user=GQqtjpoAAAAJ&hl=en&oi=ao

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
